# Generated by Django 5.2.4 on 2025-07-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('bet_type_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('bet_type_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bet_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('racecourse', models.CharField(max_length=20)),
                ('surface_type', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('horse_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('horse_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'horse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('jockey_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jockey_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jockey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('race_date', models.DateField()),
                ('num_horses', models.IntegerField()),
                ('course_id', models.CharField(max_length=4)),
                ('race_number', models.IntegerField()),
                ('weather', models.CharField(max_length=2)),
                ('track_condition', models.CharField(max_length=2)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'race',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaceStatistics',
            fields=[
                ('stat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_horses', models.IntegerField()),
                ('race_number', models.IntegerField()),
                ('weather', models.CharField(max_length=2)),
                ('horse_number', models.IntegerField()),
                ('frame_number', models.IntegerField()),
                ('style_prediction', models.TextField()),
                ('sample_size', models.IntegerField()),
                ('num_place', models.IntegerField()),
                ('num_win', models.IntegerField()),
            ],
            options={
                'db_table': 'race_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaceDetail',
            fields=[
                ('race', models.ForeignKey(db_column='race_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='keiba.race')),
                ('horse_id', models.CharField(max_length=10)),
                ('jockey_id', models.CharField(max_length=5)),
                ('horse_number', models.IntegerField()),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('style_prediction', models.TextField(blank=True, null=True)),
                ('odds', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('finish_rank', models.IntegerField(blank=True, null=True)),
                ('time_index', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'race_detail',
                'managed': False,
            },
        ),
    ]
